name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # 1. Configura os ambientes de execução
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Configurar Java 21 (Para o Allure)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 2. Instala as dependências do projeto
      - name: Instalar Dependências do Projeto
        run: npm ci

      # 3. Sobe toda a infraestrutura do Docker Compose (Exceto o Jenkins)
      - name: Subir Infraestrutura (Docker Compose)
        run: |
          docker compose up -d db redis paybank-ms-auth paybank-ms-email paybank-mf-auth

      # 4. Redireciona o nome 'paybank-mf-auth' para o localhost interno do Runner (para rodar direto na máquina do Runner (fora do Docker))
      - name: Mapear Host do Contêiner para Localhost
        run: |
          sudo echo "127.0.0.1 paybank-mf-auth" | sudo tee -a /etc/hosts

      # 5. Aguarda a API estar totalmente online antes de prosseguir
      - name: Aguardar APIs estarem 100% prontas
        run: |
          echo "Aguardando o serviço de autenticação iniciar na porta 3333..."
          until curl -s http://localhost:3333 > /dev/null; do
            echo "Aguardando inicialização..."
            sleep 2
          done
          echo "Ambiente pronto!"

      # 6. Instala navegadores e roda os testes
      - name: Instalar Navegadores do Playwright
        run: npx playwright install --with-deps

      - name: Executar Testes E2E
        run: npx playwright test

      # 7. Guarda os resultados do Allure
      - name: Guardar Resultados do Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 10