name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Subir Infraestrutura (Docker Compose)
        run: |
          docker compose up -d db redis paybank-ms-auth paybank-ms-email paybank-mf-auth
          
      # 2. Dá um tempo extra para o PostgreSQL e as APIs estarem 100% online
      - name: Aguardar Inicialização dos Serviços
        run: sleep 20

      # 3. Configura o ambiente de testes na máquina do GitHub Actions
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Configurar Java 21 (Para o Allure)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 4. Instala dependências e executa os testes localmente
      - name: Instalar Dependências do Projeto
        run: npm ci

      - name: Instalar Navegadores do Playwright
        run: npx playwright install --with-deps

      - name: Executar Testes E2E
        env:
          BASE_URL: http://localhost:3000
        run: npx playwright test

      # 5. Guarda os resultados do Allure
      - name: Guardar Resultados do Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 10